<div class="visible-lg-block">
	<a class="twitter-timeline" href="https://twitter.com/{{ env.TWITTER_ACCOUNT }}" data-widget-id="647428406687191040">Tweets de {{ env.TWITTER_ACCOUNT }}</a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>
